"""empty message

Revision ID: 97268311e829
Revises: 
Create Date: 2018-10-08 01:37:57.422553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97268311e829'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('access_token_key', sa.String(length=64), nullable=True),
    sa.Column('access_token_secret', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_id')
    )
    op.create_table('twitts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(length=280), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitts')
    op.drop_table('users')
    # ### end Alembic commands ###
